GET http://localhost:8000/movie

###

GET http://localhost:8000/movie/1234

###

POST http://localhost:8000/movie
Content-Type: application/json

{
  "title": "Avengers",
  "genre": "Action",
  "character" : "Tony Stark"
}

###

PUT http://localhost:8000/movie/69359ee00373fef006b9e3b3

###

DELETE http://localhost:8000/movie/69359ee00373fef006b9e3b3